apiVersion: v1
kind: Service
metadata:
  name: kubernetes-bootcamp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000  # 任意のNodePort番号を指定します
  selector:
    app: kubernetes-bootcamp
